### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by mseri** [ygrek/ocaml-libevent#1]
See: https://travis-ci.org/ocaml/opam-repository/builds/509893439

**Comment by rr0gi** [comment]
link is 404 now (5 years passed :penguin:) and cannot reproduce, so closing
I still have some suspicion there is bug lurking in tests/bindings, should open new issue when have more info

**Comment by ygrek** [comment]
link is 404 now (5 years passed 🐧) and cannot reproduce, so closing
I still have some suspicion there is bug lurking in tests/bindings, should open new issue when have more info
